apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "training-app.fullname" . }}-backend
  labels:
    {{- include "training-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "training-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "training-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              python init_db.py
              uvicorn app:app --host 0.0.0.0 --port 8000
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          env:
            - name: ENV
              value: "production"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: training_app
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20 