apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "training-app.fullname" . }}-frontend-config
data:
  config.js: |
    window.ENV = {
      API_URL: 'http://{{ include "training-app.fullname" . }}-backend:{{ .Values.backend.service.port }}/api'
    }; 