apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "training-app.fullname" . }}-frontend
  labels:
    {{- include "training-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "training-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "training-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: frontend-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: frontend-config
          configMap:
            name: {{ include "training-app.fullname" . }}-frontend-config 