replicaCount: 1

image:
  repository: ghcr.io/Fro1m/training-app
  tag: latest  # This will be updated by ArgoCD Image Updater
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {} 