backend:
  replicaCount: 1
  image:
    repository: fro1m/training-app
    tag: d37674b2b1b2a1cc61e64a0f3da36aa2202b3284
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

frontend:
  replicaCount: 1
  image:
    repository: fro1m/training-app-frontend
    tag: 75bb60ce3040590e515c4f03b1b7ce6e7d66ede3
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {} 