replicaCount: 1

image:
  repository: ghcr.io/your-username/training-app
  tag: 2ab100aaa7f4f64e86d9e8c0f3bddd8285a8047a
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {} 