replicaCount: 1

image:
  repository: ghcr.io/your-username/training-app
  tag: 0f98baf352ef2d4b45315e39480530243a275a29
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {} 