replicaCount: 1

image:
  repository: ghcr.io/your-username/training-app
  tag: 459a99e63a145ac9eab08c7a568c650c03843bc5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {} 