backend:
  replicaCount: 1
  image:
    repository: fro1m/training-app
    tag: 2d2ebde9fcbfc1716b83d7591e216e65ea50bce0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

frontend:
  replicaCount: 1
  image:
    repository: fro1m/training-app-frontend
    tag: 5d70453805a6371e3b7158b22ff6304a6320975d
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {} 