replicaCount: 1

image:
  repository: ghcr.io/your-username/training-app
  tag: ea7429e4564b961fcc8ffca954b39063ef2eb4a5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {} 