replicaCount: 1

image:
  repository: ghcr.io/your-username/training-app
  tag: c7896d542629870aa3d698fb14f9c6a5b5763556
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {} 