backend:
  replicaCount: 1
  image:
    repository: fro1m/training-app
    tag: 5cdd4b3a839ad625329ca5565e787ba1f4a0de47
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

frontend:
  replicaCount: 1
  image:
    repository: fro1m/training-app-frontend
    tag: 333fb35baad11bcdfc3ea9424a571beb4b73e3b3
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {} 