replicaCount: 1

image:
  repository: fro1m/training-app
  tag: 23707fb1cd9900039197f93360f7b3de86734f45
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {} 