apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: training-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Fro1m/trainingApp
    targetRevision: HEAD
    path: helm/training-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 