name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          
      - name: Run tests
        run: |
          cd backend
          python -m pytest

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create update PR
        run: |
          # Create a new branch for the update
          git checkout -b update-image-tag-${{ github.sha }}
          
          # Update the values.yaml with the new tag
          cd helm/training-app
          sed -i "s/tag: .*/tag: ${{ github.sha }}/" values.yaml
          
          # Commit and push the changes
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin update-image-tag-${{ github.sha }}
          
          # Create PR
          gh pr create \
            --title "Update image tag to ${{ github.sha }}" \
            --body "Automated update of image tag for deployment" \
            --base main \
            --head update-image-tag-${{ github.sha }} 